apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: api-refresh-data
spec:
  schedule: '*/10 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: api-refresh-data
              image: 719591212312.dkr.ecr.ap-south-1.amazonaws.com/api-server:__IMAGE_VERSION__
              command:
                - npm
                - run
                - cowin_cron
              env:
                - name: MONGODB_URL
                  valueFrom:
                    secretKeyRef:
                      key: url
                      name: api-server-mongo-creds
          restartPolicy: OnFailure
