apiVersion: batch/v1
kind: CronJob
metadata:
  name: api-refresh-data
spec:
  schedule: '*/30 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: api-refresh-data
              image: __IMAGE__NAME__
              command:
                - npm
                - run
                - cowin_cron
          restartPolicy: OnFailure
