apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-server
  name: api-server
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-server
    spec:
      containers:
        - image: __IMAGE__NAME__
          imagePullPolicy: Always
          name: india-vaccine-api-server
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  key: url
                  name: api-server-mongo-creds
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3000
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
          startupProbe:
            httpGet:
              path: /healthz
              port: 3000
      terminationGracePeriodSeconds: 30
