apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-server
  name: api-server
  namespace: default
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: api-server
  type: ClusterIP
